version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # command: python main.py
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
